manifest = "670fb36f72c21b698fd4fd73624902c8a3d22fb2861cb0fb41a39b4382b21f7b"

[[dependency]]
package = "github.com/buckaroo-pm/netsurf-parserutils"
target = "//:parserutils"

[lock."github.com/buckaroo-pm/netsurf-parserutils"]
versions = [ "branch=master" ]
revision = "bdee37e518fa178e8eaaa80fc6a8ac2eeb23f0be"
